version: 1.0.{build}
before_build:
- ps: write-host "my . script"
build:
  verbosity: minimal
on_finish:
- cmd: echo my . onfin call

  
#configuration: Release
#services:
#  - mssql2012sp1
#  - iis
#build_script:
#- ps: get-service 'MSSQL$SQL2012SP1'

#after_test:
# powershell capture command output into variable
#- ps: $version = lxc version
#- ps: echo $version
# pack lxc as aftifact for upload
#- ps: $archive = "lxc-$version-windows-amd64.zip"
#- 7z a $archive c:\gopath\bin\lxc.exe


#notifications:
#- provider: Webhook
#  url: http://requestb.in/p7cjenp7
#  method: POST
#  headers:
#    X-Api-Key: 
#     secure: 9vNz+tHM2nuER4MTf+iIbg==
#  body: >-
#    {
#        "foo":  "bar"
#    }
#  on_build_success: true
#  on_build_failure: true
#  on_build_status_changed: true


#artifacts:
#- path: src\VeryNewWebJob
#  name: VeryNewWebJob



#deploy:
#- provider: AzureWebJob
#  website: ilyaf
#  username: ilyafdepl
#  password:
#    secure: JqjMdWRH22nh8HpJCv3zVQ==
#  artifact: VeryNewWebJob
#  manually_triggered: false
#  job_schedule: '*0****'

#environment:
#  API_KEY:
#    secure: 9vNz+tHM2nuER4MTf+iIbg==


